name: finance-feeder
language: python
variables:
  - name: FINHUB_ENDPOINT
    inputType: FreeText
    description: Endpoint of Finhub
    defaultValue: 'wss://ws.finnhub.io'
    required: true
  - name: FINHUB_TOKEN
    inputType: FreeText
    description: Finhub Token
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py